import type { Metadata } from "next";
import { Pompiere, Inter } from "next/font/google";
import "@/app/styles/globals.css";

const pompiere = Pompiere({
  weight: "400",
  variable: "--font-pompiere",
});

const inter = Inter({
  weight:['100', '200', '300', '400', '500', '600', '700', '800', '900' ],
  variable: "--font-inter"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${pompiere.variable} ${inter.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}